import {
  REACT_APP_FIREBASE_KEY,
  REACT_APP_FIREBASE_AUTH,
  REACT_APP_FIREBASE_PROJECT,
  REACT_APP_FIREBASE_BUCKET,
  REACT_APP_FIREBASE_SENDER,
  REACT_APP_FIREBASE_APPID,
} from "@env";

const firebaseConfig = {
  apiKey: REACT_APP_FIREBASE_KEY,
  authDomain: REACT_APP_FIREBASE_AUTH,
  projectId: REACT_APP_FIREBASE_PROJECT,
  storageBucket: REACT_APP_FIREBASE_BUCKET,
  messagingSenderId: REACT_APP_FIREBASE_SENDER,
  appId: REACT_APP_FIREBASE_APPID,
};
export default firebaseConfig;
